# ruff: noqa: INP001
"""Generate checked-in configuration examples from Pydantic defaults."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from computer_vision.train import TrainConfig, create_training_parser

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "configs/train.example.yaml"


def render_training_defaults() -> str:
    """Render the training defaults with jsonargparse documentation comments."""
    defaults = TrainConfig().model_dump(
        mode="json",
        exclude_computed_fields=True,
    )
    parser = create_training_parser(TrainConfig)
    parser.dump_header = [
        "Training settings and defaults.",
        "Generated by scripts/generate_config_examples.py; do not edit manually.",
    ]
    parser.set_defaults(defaults)
    return parser.dump(
        parser.parse_object(defaults),
        format="yaml",
        skip_unset=False,
        with_comments=True,
    )


def main() -> int:
    """Write the generated example or check that it is current."""
    argument_parser = argparse.ArgumentParser(description=__doc__)
    argument_parser.add_argument(
        "--check",
        action="store_true",
        help="Check the checked-in example without writing it.",
    )
    options = argument_parser.parse_args()
    expected_examples = {
        OUTPUT_PATH: render_training_defaults(),
    }

    if options.check:
        stale_paths = [path for path, expected in expected_examples.items() if not path.exists() or path.read_text(encoding="utf-8") != expected]
        for path in stale_paths:
            sys.stdout.write(f"{path} is out of date; run this script without --check.\n")
        return int(bool(stale_paths))

    for path, expected in expected_examples.items():
        path.write_text(expected, encoding="utf-8")
        sys.stdout.write(f"Wrote {path}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
